[skip ci] Update Ngrok and fix update command

diff --git a/valet b/valet
--- a/valet
+++ b/valet
@@ -1,8 +1,28 @@
 #!/usr/bin/env bash
 
+set -e
+
 SOURCE="${BASH_SOURCE[0]}"
 SUDOCMDS="uninstall install start restart stop unsecure secure"
 HOMEPATH=$HOME
+
+function check_dependencies {
+    local RED='\033[1;31m'
+    local NC='\033[0m'
+    local BOOL=true
+
+    for cmd in "jq" "xsel" "certutil" "NetworkManager"; do
+        if ! [ -x "$(command -v $cmd)" ]; then
+            printf "${RED}%-15s" "$cmd"
+            printf "missing, please install the program.\n${NC}"
+            BOOL=false
+        fi
+    done
+
+    if [ "$BOOL" = "false" ]; then
+        exit 1;
+    fi
+}
 
 # If the current source is a symbolic link, we need to resolve it to an
 # actual directory name. We'll use PHP to do this easier than we can
@@ -27,11 +47,6 @@ fi
 # us to never require the end users to manually specify each sudo.
 if [[ -n $1 && $SUDOCMDS =~ $1 ]]
 then
-    if [[ ! -d "/etc/NetworkManager/dnsmasq.d" ]]
-    then
-        sudo mkdir -p "/etc/NetworkManager/dnsmasq.d"
-    fi
-
     if [[ "$EUID" -ne 0 ]]
     then
         sudo env HOME=$HOMEPATH $SOURCE "$@"
@@ -53,6 +68,8 @@ fi
 # process to retrieve the live Ngrok tunnel URL in the background.
 if [[ "$1" = "share" ]]
 then
+    check_dependencies
+    
     HOST="${PWD##*/}"
     DOMAIN=$(php "$DIR/cli/valet.php" domain)
     PORT=$(cat "$HOME/.valet/config.json" | jq -r ".port")
